#!/bin/bash

# Navigate to the project root
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Notes:
# search_disk_index script fails to use the groundtruth file derived from the fvecs file in the dataset but it can use the binary file generated by calculate_groundtruth script.
# calculate_recall script fails to use the binary file generated by calculate_groundtruth script but it can use the groundtruth file derived from the fvecs file in the dataset.
# If we follow these rules, both search_disk_index and calculate_recall scripts return the same recall value.

"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/sift/sift_base.fvecs" "${ROOT_DIR}/data/sift/sift_base.bin"
"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/sift/sift_query.fvecs" "${ROOT_DIR}/data/sift/sift_query.bin"
"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/sift/sift_learn.fvecs" "${ROOT_DIR}/data/sift/sift_learn.bin"
"${ROOT_DIR}/build/tests/utils/ivecs_to_bin" "${ROOT_DIR}/data/sift/sift_groundtruth.ivecs" "${ROOT_DIR}/data/sift/sift_groundtruth.bin"
# "${ROOT_DIR}/build/tests/utils/compute_groundtruth" float "${ROOT_DIR}/data/sift/sift_base.bin" "${ROOT_DIR}/data/sift/sift_query.bin" 100 "${ROOT_DIR}/data/sift/sift_groundtruth.bin"

"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/siftsmall/siftsmall_base.fvecs" "${ROOT_DIR}/data/siftsmall/siftsmall_base.bin"
"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/siftsmall/siftsmall_query.fvecs" "${ROOT_DIR}/data/siftsmall/siftsmall_query.bin"
"${ROOT_DIR}/build/tests/utils/fvecs_to_bin" "${ROOT_DIR}/data/siftsmall/siftsmall_learn.fvecs" "${ROOT_DIR}/data/siftsmall/siftsmall_learn.bin"
"${ROOT_DIR}/build/tests/utils/ivecs_to_bin" "${ROOT_DIR}/data/siftsmall/siftsmall_groundtruth.ivecs" "${ROOT_DIR}/data/siftsmall/siftsmall_groundtruth.bin"
# "${ROOT_DIR}/build/tests/utils/compute_groundtruth" float "${ROOT_DIR}/data/siftsmall/siftsmall_base.bin" "${ROOT_DIR}/data/siftsmall/siftsmall_query.bin" 100 "${ROOT_DIR}/data/siftsmall/siftsmall_groundtruth.bin"
